### ISSUE TITLE
gateway 中 Oauth2  提示 token无效

### ISSUE THREAD

**Issue by 292734964** [dromara/Sa-Token#147]
### 使用版本:
 sa-token-reactor-spring-boot-starter  1.26.0

   
### 报错信息：
cn.dev33.satoken.exception.NotLoginException: token无效
	at cn.dev33.satoken.exception.NotLoginException.newInstance(NotLoginException.java:121)
	at cn.dev33.satoken.stp.StpLogic.getLoginId(StpLogic.java:408)
	at cn.dev33.satoken.stp.StpLogic.checkLogin(StpLogic.java:388)
	at cn.dev33.satoken.stp.StpUtil.checkLogin(StpUtil.java:154)
	at com.inm.rc.gateway.oauth2.TokenConfigure.lambda$null$0(TokenConfigure.java:39)
	at cn.dev33.satoken.router.SaRouter.match(SaRouter.java:88)
	at com.inm.rc.gateway.oauth2.TokenConfigure.lambda$getReactorFilter$1(TokenConfigure.java:39)
	at cn.dev33.satoken.reactor.filter.SaReactorFilter.lambda$filter$3(SaReactorFilter.java:166)
	at cn.dev33.satoken.router.SaRouter.match(SaRouter.java:113)
	at cn.dev33.satoken.reactor.filter.SaReactorFilter.filter(SaReactorFilter.java:164)
	at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:121)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
	at org.springframework.cloud.sleuth.instrument.web.TraceWebFilter$MonoWebFilterTrace.subscribe(TraceWebFilter.java:180)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:70)
	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)
	at reactor.netty.http.server.HttpServerHandle.onStateChange(HttpServerHandle.java:64)
	at reactor.netty.tcp.TcpServerBind$ChildObserver.onStateChange(TcpServerBind.java:226)
	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:442)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:366)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:181)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:259)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

### 希望结果：
正常的登录验证

### 复现步骤：

备注：您提供的信息越充足，我们将越能快速的定位错误 

gateway 引入

        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-reactor-spring-boot-starter</artifactId>
            <version>1.26.0</version>
        </dependency>
        
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-dao-redis-jackson</artifactId>
            <version>1.26.0</version>
        </dependency>
        <dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-lang3</artifactId>
		<version>3.5</version>
	</dependency>

子服务 引入

        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-spring-boot-starter</artifactId>
            <version>1.26.0</version>
        </dependency>

        
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-oauth2</artifactId>
            <version>1.26.0</version>
        </dependency>
        
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-dao-redis-jackson</artifactId>
            <version>1.26.0</version>
        </dependency>
        <dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-lang3</artifactId>
		<version>3.5</version>
	</dependency>

gateway 配置
# sa-token配置
sa-token: 
    # token 前缀
    token-prefix: Bearer
    # token名称 (同时也是cookie名称)
    token-name: Authorization
    # OAuth2.0 配置 
    oauth2: 
        is-code: true
        is-implicit: true
        is-password: true
        is-client: true
子服务 配置
# sa-token配置
sa-token: 
    # token 前缀
    token-prefix: Bearer
    # token名称 (同时也是cookie名称)
    token-name: Authorization

gateway 截拦器 
   @Bean
    public SaReactorFilter getReactorFilter() {
        List<String> ignoreUrls= ignoreUrlsConfig.getUrls();
        String[] ignore=ignoreUrls.toArray(new String[ignoreUrls.size()]);
        log.info("---------- 开放地址->{}",ignore);
        return new SaReactorFilter()
                // 拦截地址
                .addInclude("/**")
                // 开放地址
                .addExclude(ignore)
                // 鉴权方法：每次访问进入
                .setAuth(r -> {
                    // 登录验证 -- 拦截所有路由，并排除/oauth2 用于开放登录
                    SaRouter.match("/**", "/inm-rc-auth/oauth2/**", () -> StpUtil.checkLogin());
                })
                // 异常处理方法：每次setAuth函数出现异常时进入
                .setError(e -> {
                    log.info("---------- sa全局异常 ->{}",e);
                    return Result.error(e.getMessage());
                });
    }

**Comment by click33** [comment]
你是拿 oauth2 的Token 去 StpUtil 验证？

**Comment by 292734964** [comment]
@click33 是的。
但发现，并不能这么玩。
使用Oauth2
在gateway如何验证呢？
应用调用什么方法？

**Comment by click33** [comment]
参考：https://sa-token.dev33.cn/doc/index.html#/oauth2/oauth2-dev
