### ISSUE TITLE
使用官方例子实现注解鉴权，正确返回了字符串集合，但是没有权限的话会抛出空指针异常

### ISSUE THREAD

**Issue by miraclelll** [dromara/Sa-Token#197]
### 使用版本:
1.28.0

### 报错信息：
java.lang.NullPointerException: null
	at cn.dev33.satoken.util.SaFoxUtil.vagueMatch(SaFoxUtil.java:158) ~[sa-token-core-1.28.0.jar:na]
	at cn.dev33.satoken.action.SaTokenActionDefaultImpl.hasElement(SaTokenActionDefaultImpl.java:90) ~[sa-token-core-1.28.0.jar:na]
	at cn.dev33.satoken.strategy.SaStrategy.lambda$new$2(SaStrategy.java:66) ~[sa-token-core-1.28.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.hasElement(StpLogic.java:1685) ~[sa-token-core-1.28.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.checkPermissionAnd(StpLogic.java:1221) ~[sa-token-core-1.28.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.checkByAnnotation(StpLogic.java:1402) ~[sa-token-core-1.28.0.jar:na]
	at cn.dev33.satoken.action.SaTokenActionDefaultImpl.validateAnnotation(SaTokenActionDefaultImpl.java:133) ~[sa-token-core-1.28.0.jar:na]
	at cn.dev33.satoken.strategy.SaStrategy.lambda$new$4(SaStrategy.java:88) ~[sa-token-core-1.28.0.jar:na]
	at cn.dev33.satoken.strategy.SaStrategy.lambda$new$3(SaStrategy.java:79) ~[sa-token-core-1.28.0.jar:na]
	at cn.dev33.satoken.interceptor.SaAnnotationInterceptor.preHandle(SaAnnotationInterceptor.java:40) ~[sa-token-spring-boot-starter-1.28.0.jar:na]
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148) ~[spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1062) ~[spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.12.jar:5.3.12]

### 希望结果：
按照接口查询的list结果实现注解鉴权

### 复现步骤：
编写StpInterfaceImpl实现StpInterface后，重写getPermissionList接口后，返回字符串集合，结果提示空指针
![image](https://user-images.githubusercontent.com/43053955/144556868-67871d9d-b8ed-4f3e-8fa9-cb366bed2f0c.png)

**Comment by click33** [comment]
getPermissionList 返回数据是不是包含 null 了

**Comment by miraclelll** [comment]
> getPermissionList 返回数据是不是包含 null 了

没有包含null，我的截图里面可以看到长度为19的arraylist中下标0-18都是有内容的

**Comment by miraclelll** [comment]
> getPermissionList 返回数据是不是包含 null 了

解决了，数组的问题，下标被弄乱了
