### ISSUE TITLE
Http Basic 认证 Spring Boot 2 中不弹登录框

### ISSUE THREAD

**Issue by sunxyz** [dromara/Sa-Token#201]
### 使用版本:
1.28.0

### 报错信息：
请提供报错的详细信息
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Dec 17 17:18:21 CST 2021
There was an unexpected error (type=Internal Server Error, status=500).
cn.dev33.satoken.exception.NotBasicAuthException: no basic auth
cn.dev33.satoken.exception.SaTokenException: cn.dev33.satoken.exception.NotBasicAuthException: no basic auth
	at cn.dev33.satoken.filter.SaServletFilter.lambda$new$1(SaServletFilter.java:111)
	at cn.dev33.satoken.filter.SaServletFilter.doFilter(SaServletFilter.java:167)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: cn.dev33.satoken.exception.NotBasicAuthException: no basic auth
	at cn.dev33.satoken.basic.SaBasicTemplate.throwNotBasicAuthException(SaBasicTemplate.java:27)
	at cn.dev33.satoken.basic.SaBasicTemplate.check(SaBasicTemplate.java:74)
	at cn.dev33.satoken.basic.SaBasicTemplate.check(SaBasicTemplate.java:60)
	at cn.dev33.satoken.basic.SaBasicUtil.check(SaBasicUtil.java:35)
	at com.sddx.yfcx.dataporter.DataPorterApplication.lambda$null$0(DataPorterApplication.java:47)
	at cn.dev33.satoken.router.SaRouterStaff.check(SaRouterStaff.java:225)
	at cn.dev33.satoken.router.SaRouterStaff.match(SaRouterStaff.java:266)
	at cn.dev33.satoken.router.SaRouter.match(SaRouter.java:269)
	at com.sddx.yfcx.dataporter.DataPorterApplication.lambda$getSaServletFilter$1(DataPorterApplication.java:45)
	at cn.dev33.satoken.filter.SaServletFilter.lambda$doFilter$3(SaServletFilter.java:160)
	at cn.dev33.satoken.router.SaRouterStaff.check(SaRouterStaff.java:225)
	at cn.dev33.satoken.filter.SaServletFilter.doFilter(SaServletFilter.java:158)

### 希望结果：

弹登录框

### 复现步骤：
1.引入pom依赖

2.配置bean
```
@Bean
public SaServletFilter getSaServletFilter() {
    return new SaServletFilter()
            .addInclude("/**").addExclude("/favicon.ico")
            .setAuth(obj -> {
                SaRouter.match("/api/**", () -> SaBasicUtil.check("sa:123456"));
            });
}
```
3.浏览器访问

**Comment by sunxyz** [comment]
已fix
第二部配置bean如下
```
@Bean
    public SaServletFilter getSaServletFilter() {
        return new SaServletFilter()
                .addInclude("/**").addExclude("/favicon.ico")
                .setAuth(obj -> {
                    SaRouter.match("/api/**", (r) -> {
                        try {
                            SaBasicUtil.check("sa:123456");
                        } catch (NotBasicAuthException e) {
                            r.back();
                        }
                    });
                });
    }
```

**Comment by click33** [comment]
👍
