### ISSUE TITLE
全局过滤器鉴权异常-非Web上下文无法获取Request

### ISSUE THREAD

**Issue by AlberZ1989** [dromara/Sa-Token#212]
### 使用版本:
1.28.0

使用SaServletFilter鉴权..
SaHolder.getRequest 报错

### 报错信息：
cn.dev33.satoken.exception.SaTokenException: 非Web上下文无法获取Request
	at cn.dev33.satoken.spring.SpringMVCUtil.getRequest(SpringMVCUtil.java:25)
	at cn.dev33.satoken.spring.SaTokenContextForSpring.getRequest(SaTokenContextForSpring.java:24)
	at cn.dev33.satoken.context.SaHolder.getRequest(SaHolder.java:21)
	at cn.dev33.satoken.router.SaRouter.isMatchCurrURI(SaRouter.java:103)
	at cn.dev33.satoken.router.SaRouterStaff.match(SaRouterStaff.java:83)
	at cn.dev33.satoken.router.SaRouter.match(SaRouter.java:161)
	at cn.dev33.satoken.filter.SaServletFilter.doFilter(SaServletFilter.java:158)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:97)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by click33** [comment]
具体代码贴一下

**Comment by AlberZ1989** [comment]
@Configuration
public class SaTokenConfigure {

    @Value("#{'${sa-token.ignore}'.split(',')}")
    private List<String> ignoreRoutes;

    @Autowired
    StcPermissionService stcPermissionService;

    /**
     * 注册 [Sa-Token全局过滤器]
     */
    @Bean
    public SaServletFilter getSaServletFilter() {
        List<StcPermission> permissions = stcPermissionService.getAllPermissions(null);

        return new SaServletFilter()

                // 指定 拦截路由 与 放行路由
                .addInclude("/**")
                .setExcludeList(ignoreRoutes)
                // 认证函数: 每次请求执行
                .setAuth(obj -> {
                    System.out.println("---------- 进入Sa-Token全局认证 -----------");
                    // 登录认证 -- 拦截所有路由，并排除/user/doLogin 用于开放登录
                    SaRouter.match("/**", "/login", StpUtil::checkLogin);

                    boolean isMatch = false;

                    for(StcPermission permission : permissions){
                        if(StrUtil.isEmpty(permission.getPermissionRoute())){
                            continue;
                        }
                        if(SaRouter.isMatchCurrURI(permission.getPermissionRoute())){
                            isMatch = true;
                            SaRouter.match(permission.getPermissionRoute(), r -> StpUtil.checkPermission(permission.getPermissionName()));
                            break;
                        }

                        String extraRoutes = permission.getExtraRoutes();

        				//关联路由为空则跳过关联路由鉴权处理
                        if(StrUtil.isEmpty(extraRoutes)){
                            continue;
                        }
                        for(String extra: extraRoutes.split(ComContext.SPLIT_REGEX)){
                            if(SaRouter.isMatchCurrURI(extra)){
                                isMatch = true;
                            }
                            SaRouter.match(extra, r -> StpUtil.checkPermission(permission.getPermissionName()));
                            break;
                        }
                    }

                    if(!isMatch){
                        NotPermissionException.throwByNull(null, "无访问权限!");
                    }
                })
                // 异常处理函数：每次认证函数发生异常时执行此函数
                .setError(e -> {
                    e.printStackTrace();
                    return ApiResult.fail(e.getMessage());
                })

                ;
    }
}

**Comment by AlberZ1989** [comment]
/**
     * Http请求监听器
     *
     * @Author alberz
     * @Date 2022-01-19 15:23:11
     */
    @Bean
    public RequestContextListener requestContextListener(){
        return new RequestContextListener();
    }

加了个http 监听器,就正常了....

**Comment by AlberZ1989** [comment]
加监听器没解决

**Comment by Queensbarry** [comment]
可能是根据文档的第一点开启了 `@EnableWebMvc` 注解，尝试删除上述注解。在尝试关闭后功能依然正常，SpringBoot 版本是 2.6.4

**Comment by yemx910501** [comment]
> 可能是根据文档的第一点开启了 `@EnableWebMvc` 注解，尝试删除上述注解。在尝试关闭后功能依然正常，SpringBoot 版本是 2.6.4

我将 `@EnableWebMvc` 注解删除后，已经正常了。
