### ISSUE TITLE
在spring data reactive中使用 某些StpUtil函数报错未成功初始化上下文

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [dromara/Sa-Token#263]
### 报错信息：
```
cn.dev33.satoken.exception.SaTokenException: 未成功初始化上下文
	at cn.dev33.satoken.context.SaTokenContextForThreadLocalStorage.getBoxNotNull(SaTokenContextForThreadLocalStorage.java:54) ~[sa-token-core-1.30.0.jar:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

Original Stack Trace:
		at cn.dev33.satoken.context.SaTokenContextForThreadLocalStorage.getBoxNotNull(SaTokenContextForThreadLocalStorage.java:54) ~[sa-token-core-1.30.0.jar:na]
		at cn.dev33.satoken.context.SaTokenContextForThreadLocalStorage.getStorage(SaTokenContextForThreadLocalStorage.java:83) ~[sa-token-core-1.30.0.jar:na]
		at cn.dev33.satoken.context.SaTokenContextForThreadLocal.getStorage(SaTokenContextForThreadLocal.java:32) ~[sa-token-core-1.30.0.jar:na]
		at cn.dev33.satoken.context.SaHolder.getStorage(SaHolder.java:48) ~[sa-token-core-1.30.0.jar:na]
		at cn.dev33.satoken.stp.StpLogic.setTokenValueToStorage(StpLogic.java:133) ~[sa-token-core-1.30.0.jar:na]
		at cn.dev33.satoken.stp.StpLogic.setTokenValue(StpLogic.java:119) ~[sa-token-core-1.30.0.jar:na]
		at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:284) ~[sa-token-core-1.30.0.jar:na]
		at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:253) ~[sa-token-core-1.30.0.jar:na]
		at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:105) ~[sa-token-core-1.30.0.jar:na]
```
### 报错代码
```
return userService
            .userLoginByNameAndPassword(user.userName!!, user.password!!)
            .log()
            .map {
                StpUtil.login(it.id) // 报错
                LoginInfo(
                    it,
                    StpUtil.getTokenInfo() // 报错
                )
            }
```

```
@Repository
interface UserRepository: ReactiveMongoRepository<User, String> {
    fun findByUserNameAndPassword(name: String, password: String): Mono<User>
}
```

#### 如果不和ReactiveRepository用不会报错
```
fun test3(): MR {
        return Mono.just(1)
            .map {
                StpUtil.login(it)
                result200(StpUtil.getTokenInfo())
            }
    }
```

**Comment by click33** [comment]
参考这里二次设置一下上下文：
https://github.com/dromara/sa-token/blob/dev/sa-token-demo/sa-token-demo-webflux/src/main/java/com/pj/test/TestController.java

**Comment by ANUGLYPLUGIN** [comment]
> 参考这里二次设置一下上下文： https://github.com/dromara/sa-token/blob/dev/sa-token-demo/sa-token-demo-webflux/src/main/java/com/pj/test/TestController.java

不好意思这两天没看，已解决,  谢谢
```
              userService.xxx()
              .log()
              .flatMap { u ->
                SaReactorHolder.getContext().map {
                    StpUtil.login(u.id)
                    result200(object {
                        val tokenInfo = StpUtil.getTokenInfo()
                    })
                }
            }
```
