### ISSUE TITLE
SpringBoot3.0RC版本中报错

### ISSUE THREAD

**Issue by ijry** [dromara/Sa-Token#337]
未初始化任何有效上下文处理

**Comment by click33** [comment]
尚未适配 springboot 3.0

**Comment by ijry** [comment]
可以适配一下，马上年底3.0发布了。

**Comment by click33** [comment]
已经上计划了，下几个版本会考虑适配

**Comment by ijry** [comment]
有临时方案用吗，我在引入用3.0了。

**Comment by click33** [comment]
暂时没有，，，

**Comment by ijry** [comment]
`
cn.dev33.satoken.exception.SaTokenException: 未初始化任何有效上下文处理器
	at cn.dev33.satoken.context.SaTokenContextDefaultImpl.getStorage(SaTokenContextDefaultImpl.java:52)
	at cn.dev33.satoken.context.SaHolder.getStorage(SaHolder.java:49)
	at cn.dev33.satoken.stp.StpLogic.setTokenValueToStorage(StpLogic.java:149)
	at cn.dev33.satoken.stp.StpLogic.setTokenValue(StpLogic.java:130)
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:333)
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:292)
	at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:130)
	at com.jiangruyi.summer.core.controller.UserController.login(UserController.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:804)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1003)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:906)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:709)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:880)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:792)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:356)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:870)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1762)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

`

**Comment by junwangit** [comment]
1、springboot3.0 使用Servlet 6.0

自定义实现 SaRequestForServlet.java、 SaResponseForServlet.java、 SaStorageForServlet.java，替换为Servlet 6.0规范
自定义实现SaTokenContextForSpring，然后注入 SaManager.setSaTokenContext(new SaTokenContextForSpring());


2、springboot3.0已经废弃spring.factories注册方式

新的注册方式使用META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

载入配置
cn.dev33.satoken.spring.SaBeanRegister
cn.dev33.satoken.spring.SaBeanInject
cn.dev33.satoken.spring.sso.SaSsoBeanRegister
cn.dev33.satoken.spring.sso.SaSsoBeanInject
cn.dev33.satoken.spring.oauth2.SaOAuth2BeanRegister
cn.dev33.satoken.spring.oauth2.SaOAuth2BeanInject

齐活，这样完美解决3.0兼容性问题

**Comment by npuzl** [comment]
> 1、springboot3.0 使用Servlet 6.0
> 
> 自定义实现 SaRequestForServlet.java、 SaResponseForServlet.java、 SaStorageForServlet.java，替换为Servlet 6.0规范 自定义实现SaTokenContextForSpring，然后注入 SaManager.setSaTokenContext(new SaTokenContextForSpring());
> 
> 2、springboot3.0已经废弃spring.factories注册方式
> 
> 新的注册方式使用META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
> 
> 载入配置 cn.dev33.satoken.spring.SaBeanRegister cn.dev33.satoken.spring.SaBeanInject cn.dev33.satoken.spring.sso.SaSsoBeanRegister cn.dev33.satoken.spring.sso.SaSsoBeanInject cn.dev33.satoken.spring.oauth2.SaOAuth2BeanRegister cn.dev33.satoken.spring.oauth2.SaOAuth2BeanInject
> 
> 齐活，这样完美解决3.0兼容性问题

请问有具体实现吗，想直接一抄
