### ISSUE TITLE
与 SpringBoot 3.0 集成问题

### ISSUE THREAD

**Issue by leanderli** [dromara/Sa-Token#348]
### 建议增加的新功能:

兼容SpringBoot 3.0

### 应用场景阐述：

集成SpringBoot 3.0调用StpUtil.login方法时报错：cn.dev33.satoken.exception.InvalidContextException: 未能获取有效的上下文处理器

详细错误日志：

cn.dev33.satoken.exception.InvalidContextException: 未能获取有效的上下文处理器
	at cn.dev33.satoken.context.SaTokenContextDefaultImpl.getStorage(SaTokenContextDefaultImpl.java:53) ~[sa-token-core-1.33.0.jar:na]
	at cn.dev33.satoken.context.SaHolder.getStorage(SaHolder.java:49) ~[sa-token-core-1.33.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.setTokenValueToStorage(StpLogic.java:150) ~[sa-token-core-1.33.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.setTokenValue(StpLogic.java:131) ~[sa-token-core-1.33.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:334) ~[sa-token-core-1.33.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:311) ~[sa-token-core-1.33.0.jar:na]
	at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:154) ~[sa-token-core-1.33.0.jar:na]

< 备注：请尽量详细描述功能应用场景 >

**Comment by vicykie** [comment]
spring boot 3 现在有问题，全部使用的jakarta，很多类包名变化了

**Comment by click33** [comment]
正在适配 SpringBoot 3.0 中...
