### ISSUE TITLE
NoSuchMethodError: 'org.apache.dubbo.rpc.RpcContext.getServerContext()'

### ISSUE THREAD

**Issue by magese** [dromara/Sa-Token#376]
查看dubbo源码中是存在该方法的：
```java
    /**
     * get server side context. ( A <-- B , in B side)
     *
     * @return server context
     */
    public static RpcContextAttachment getServerContext() {
        return new RpcServerContextAttachment();
    }
```

并且在代码中直接调用 `RpcContext.getServerContext()` 是没有问题的，但是框架使用该方法是就会抛出 `NoSuchMethodError` ，希望能尽快修复。

### 使用版本:
<spring-boot.version>3.0.1</spring-boot.version>
<spring-cloud.version>2022.0.0</spring-cloud.version>
<spring-cloud-alibaba.version>2022.0.0.0-RC1</spring-cloud-alibaba.version>
<dubbo.version>3.2.0-beta.3</dubbo.version>
<sa-token.version>1.34.0</sa-token.version>

### 报错信息：
java.lang.NoSuchMethodError: 'org.apache.dubbo.rpc.RpcContext org.apache.dubbo.rpc.RpcContext.getServerContext()'
	at cn.dev33.satoken.context.dubbo.model.SaStorageForDubbo.set(SaStorageForDubbo.java:44)
	at cn.dev33.satoken.context.dubbo.model.SaStorageForDubbo.set(SaStorageForDubbo.java:13)
	at cn.dev33.satoken.stp.StpLogic.setTokenValueToStorage(StpLogic.java:161)
	at cn.dev33.satoken.stp.StpLogic.setTokenValue(StpLogic.java:131)
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:334)
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:293)
	at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:135)

### 希望结果：
dubbo调用正常

### 复现步骤：
通过RPC调用登录接口

**Comment by click33** [comment]
尚未适配 dubbo3

**Comment by magese** [comment]
> 尚未适配 dubbo3

有计划支持吗？

**Comment by click33** [comment]
有
