### ISSUE TITLE
SSO服务端校验通过重定向后一直闪屏

### ISSUE THREAD

**Issue by strongyc** [dromara/Sa-Token#406]
请在以下地址复制 issue 模板进行提交：
https://sa-token.cc/doc.html#/fun/issue-template
案例H5，SSO服务端校验通过重定向后一直闪屏

**Comment by strongyc** [comment]
官方提供的SSO中，获取URL报错
![image](https://user-images.githubusercontent.com/51156342/226502588-ad07557e-f5f0-4efc-8b59-43a3d5f56f94.png)

**Comment by click33** [comment]
把异常堆栈截全点我看

**Comment by strongyc** [comment]
java.lang.NullPointerException
	at cn.dev33.satoken.sso.SaSsoTemplate.buildServerAuthUrl(SaSsoTemplate.java:358)
	at cn.dev33.satoken.sso.SaSsoUtil.buildServerAuthUrl(SaSsoUtil.java:160)
	at ltd.newbee.cloud.modular.web.H5Controller.getSsoAuthUrl(H5Controller.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/226538596-1d470024-074f-4566-9f9f-ebe9bebc9c47.png)
bao报错接口

**Comment by click33** [comment]
前端给 clientLoginUrl 参数传值了吗

**Comment by strongyc** [comment]
sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  max-login-count: -1
  token-style: random-32
  is-log: false
  is-print: false
  # ------- SSO-模式二相关配置
  sso:
    # Ticket有效期 (单位: 秒)，默认五分钟
    ticket-timeout: 300
    # 所有允许的授权回调地址
    # 是否打开单点注销功能
    is-slo: true
#    auth-url: http://127.0.0.1:8099/sso/auth
    auth-url: http://localhost:8000/login
    # SSO-Server端 统一认证地址
    #    auth-url:  http://localhost:8000/login
    # ------- SSO-模式三相关配置 （下面的配置在SSO模式三并且 is-slo=true 时打开）
    # 是否打开模式三
    isHttp: true
    # 接口调用秘钥（用于SSO模式三的单点注销功能）
    #    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # ---- 除了以上配置项，你还需要为 Sa-Token 配置http请求处理器（文档有步骤说明）
  #    is-http: true

  # sa-token alone-redis configuration
  alone-redis:
    database: 2
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    username: ${spring.redis.username}
    password: ${spring.redis.password}
    timeout: ${spring.redis.timeout}
    lettuce:
      pool:
        max-active: ${spring.redis.lettuce.pool.max-active}
        max-wait: ${spring.redis.lettuce.pool.max-wait}
        max-idle: ${spring.redis.lettuce.pool.max-idle}
        min-idle: ${spring.redis.lettuce.pool.min-idle}
客户端配置

**Comment by click33** [comment]
报错空指针，应该是前端没有提交 clientLoginUrl  参数

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/226543231-a4885529-4866-44da-bd35-43d6ac81e5d6.png)
传值了啊，这个接口也报错，是我配置的有问题吗

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/226543400-2d6c37bf-7ad9-4c1d-9324-e45acc78344e.png)

**Comment by click33** [comment]
![image](https://user-images.githubusercontent.com/36243476/226543587-5fd2c32a-4d68-4817-a64e-b02606f89d32.png)

**Comment by click33** [comment]
有没有传值，从f12控制台看一下http报文信息

**Comment by strongyc** [comment]
感谢解答，应该是我这里的问题
