### ISSUE TITLE
集成redis后，连接过一段时间就会断开并抛出异常

### ISSUE THREAD

**Issue by heyyuyu** [dromara/Sa-Token#436]
### 使用版本:1.34.0
springboot配置如下:
```
spring:
  application:
    name: gateway
  redis:
    database: 0
    host: ******
    port: ******
    password: ******
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
```

pom配置如下：
```
 <dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-pool2</artifactId>
    <version>2.11.1</version>
</dependency>
<dependency>
    <groupId>cn.dev33</groupId>
    <artifactId>sa-token-dao-redis-jackson</artifactId>
    <version>1.34.0</version>
</dependency>
<dependency>
    <groupId>cn.dev33</groupId>
    <artifactId>sa-token-reactor-spring-boot-starter</artifactId>
    <version>1.34.0</version>
</dependency>
```

### 报错信息：
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ cn.dev33.satoken.reactor.filter.SaReactorFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/login" [ExceptionHandlingWebHandler]
Stack trace:
		at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:275) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:68) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:266) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:57) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:60) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:53) ~[spring-data-redis-2.3.9.RELEASE.jar:2.3.9.RELEASE]
		at cn.dev33.satoken.dao.SaTokenDaoRedisJackson.getObject(SaTokenDaoRedisJackson.java:204) ~[sa-token-dao-redis-jackson-1.34.0.jar:na]
		at cn.dev33.satoken.dao.SaTokenDao.getSession(SaTokenDao.java:118) ~[sa-token-core-1.34.0.jar:na]
		at cn.dev33.satoken.stp.StpLogic.getSessionBySessionId(StpLogic.java:873) ~[sa-token-core-1.34.0.jar:na]
		at cn.dev33.satoken.stp.StpLogic.getSessionByLoginId(StpLogic.java:897) ~[sa-token-core-1.34.0.jar:na]
		at cn.dev33.satoken.stp.StpLogic.createLoginSession(StpLogic.java:365) ~[sa-token-core-1.34.0.jar:na]
		at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:331) ~[sa-token-core-1.34.0.jar:na]
		at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:293) ~[sa-token-core-1.34.0.jar:na]
		at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:135) ~[sa-token-core-1.34.0.jar:na]

### 复现步骤：

< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by ly-chn** [comment]
看起来与sa-token无关, 建议检查redis网络以及性能情况. 百度搜索关键词`RedisException: java.io.IOException: 远程主机强迫关闭了一个现有的连接。`

**Comment by click33** [comment]
这是 RedisTemplate 的问题，Sa-Token 也属于受害者

**Comment by zhyank** [comment]
min-idle: 0

**Comment by zhyank** [comment]
redis的tcp-keepalive的时长稍微配置长一点，可以减少这个问题发生的频率
