### ISSUE TITLE
java20 缺少jaxb-api包，需要手动导入

### ISSUE THREAD

**Issue by doublewaters** [dromara/Sa-Token#460]
### 使用版本:
使用java20 springboot3.1.0
```
<dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-spring-boot3-starter</artifactId>
            <version>1.34.0</version>
</dependency>
```

### 涉及的功能模块：在测试使用sso的相关demo中报错

```
------ 发起请求：http://localhost:9000/sso/signout?loginId=10001&timestamp=1685611852219&nonce=UKIh4U33qMZNR0vaQnKJ&sign=f5cab84218bd11d7508f41f64d48093c
2023-06-01T17:30:52.220+08:00  INFO 18652 --- [nio-8088-exec-6] c.d.forest.logging.DefaultLogHandler     : [Forest] Request (okhttp3): 
	GET http://localhost:9000/sso/signout?loginId=10001&timestamp=1685611852219&nonce=UKIh4U33qMZNR0vaQnKJ&sign=f5cab84218bd11d7508f41f64d48093c HTTP
2023-06-01T17:30:52.896+08:00  INFO 18652 --- [nio-8088-exec-6] c.d.forest.logging.DefaultLogHandler     : [Forest] Response: Status = 200, Time = 675ms
2023-06-01T17:30:52.898+08:00  WARN 18652 --- [nio-8088-exec-6] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [cn.dev33.satoken.sso.exception.SaSsoException: Handler dispatch failed: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException]
cn.dev33.satoken.sso.exception.SaSsoException: Handler dispatch failed: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at cn.dev33.satoken.sso.SaSsoProcessor.ssoLogoutType3(SaSsoProcessor.java:358)
	at cn.dev33.satoken.sso.SaSsoProcessor.ssoLogout(SaSsoProcessor.java:304)
	at cn.dev33.satoken.sso.SaSsoProcessor.clientDister(SaSsoProcessor.java:228)
	at com.github.doublewaters.saclient.Controller.SsoClientController.ssoRequest(SsoClientController.java:46)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1623)
````

#### 原因：
是由于缺少jaxb-api包导致的。在Java 8以及以前的版本，是默认包含jaxb这个jar包的；但是在java SE 9.0就不再包含着个包了，如果使用则需要手动引进。

> JAXB API是java EE 的API，因此在java SE 9.0 中不再包含这个 Jar 包。 java 9  
> 中引入了模块的概念，默认情况下，Java SE中将不再包含java EE 的Jar包 而在 java 6/7/8 时关于这个API  
> 都是捆绑在一起的
我经过以下步骤测试：
手动导入以下包
```
<!--解决Handler dispatch failed;nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter-->
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.1.1</version>
		</dependency>
```
手动导入包后可以正常运行，可以在sa-token-spring-boot3-starter的pom中引入相关依赖

**Comment by click33** [comment]
可是我查阅了一下 sa-token-sso 模块，并没有发现使用任何与 JAXBException 有关的 API 呀，你是不是对代码做了特定更改？希望可以提供一个复现问题的 demo

**Comment by doublewaters** [comment]
https://github.com/doublewaters/sa-sso
这是我的代码，我在学习使用java20 并尝试写一个关于sso的例子，我想应该是在发送访问请求的时候报错了，可能不是sa-token的原因
![image](https://github.com/dromara/Sa-Token/assets/35893428/efc37522-bf55-4d60-afbe-5166905af047)
