### ISSUE TITLE
未能获取有效的上下文

### ISSUE THREAD

**Issue by Xsvhii** [dromara/Sa-Token#506]
### 使用版本: 
springboot:3.1.2
spring-boot-starter-data-redis-reactive
spring-boot-starter-webflux
sa-token-reactor-spring-boot3-starter:1.35.0.RC
sa-token-redis-jackson:1.35.0.RC

### 报错信息：cn.dev33.satoken.exception.InvalidContextException: 未能获取有效的上下文
	at cn.dev33.satoken.context.SaTokenContextForThreadLocalStorage.getBoxNotNull(SaTokenContextForThreadLocalStorage.java:72) ~[sa-token-core-1.35.0.RC.jar:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler com.gientech.dmfc.ota.system.user.controller.SystemUserController#login(LoginEntity) [DispatcherHandler]
Original Stack Trace:
		at cn.dev33.satoken.context.SaTokenContextForThreadLocalStorage.getBoxNotNull(SaTokenContextForThreadLocalStorage.java:72) ~[sa-token-core-1.35.0.RC.jar:na]
		at cn.dev33.satoken.context.SaTokenContextForThreadLocalStorage.getStorage(SaTokenContextForThreadLocalStorage.java:101) ~[sa-token-core-1.35.0.RC.jar:na]
		at cn.dev33.satoken.context.SaTokenContextForThreadLocal.getStorage(SaTokenContextForThreadLocal.java:49) ~[sa-token-core-1.35.0.RC.jar:na]
		at cn.dev33.satoken.context.SaHolder.getStorage(SaHolder.java:69) ~[sa-token-core-1.35.0.RC.jar:na]
		at cn.dev33.satoken.stp.StpLogic.setTokenValueToStorage(StpLogic.java:218) ~[sa-token-core-1.35.0.RC.jar:na]
		at cn.dev33.satoken.stp.StpLogic.setTokenValue(StpLogic.java:198) ~[sa-token-core-1.35.0.RC.jar:na]
		at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:441) ~[sa-token-core-1.35.0.RC.jar:na]
		at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:397) ~[sa-token-core-1.35.0.RC.jar:na]
		at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:164) ~[sa-token-core-1.35.0.RC.jar:na]
		at com.gientech.dmfc.ota.system.user.service.impl.SystemUserServiceImpl.lambda$login$6(SystemUserServiceImpl.java:134) ~[classes/:na]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onNext(FluxUsingWhen.java:345) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.5.8.jar:3.5.8]
		at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onNext(RedisPublisher.java:890) ~[lettuce-core-6.2.5.RELEASE.jar:6.2.5.RELEASE]
		at io.lettuce.core.RedisPublisher$RedisSubscription.onNext(RedisPublisher.java:291) ~[lettuce-core-6.2.5.RELEASE.jar:6.2.5.RELEASE]
		at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:777) ~[lettuce-core-6.2.5.RELEASE.jar:6.2.5.RELEASE]
		at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65) ~[lettuce-core-6.2.5.RELEASE.jar:6.2.5.RELEASE]
		at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:747) ~[lettuce-core-6.2.5.RELEASE.jar:6.2.5.RELEASE]
		at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:682) ~[lettuce-core-6.2.5.RELEASE.jar:6.2.5.RELEASE]
		at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:599) ~[lettuce-core-6.2.5.RELEASE.jar:6.2.5.RELEASE]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
		at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

### 复现步骤：
@Configuration
@Slf4j
public class SaTokenConfig {
    @Bean
    public SaReactorFilter getSaReactorFilter() {
        return new SaReactorFilter()
                // 指定 [拦截路由]
                .addInclude("/**")
                // 指定 [放行路由]
                .addExclude("/system/user/login", "/**")
                // 指定[认证函数]: 每次请求执行
                .setAuth(obj -> {
                    SaRouter.match("/**", StpUtil::checkLogin);
                })
                // 指定[异常处理函数]：每次[认证函数]发生异常时执行此函数
                .setError(e -> {
                    throw new BusinessException(e.getMessage());
                });
    }
}

### 登录方法:
    @Override
    public Mono<SaTokenInfo> login(LoginEntity loginEntity) {
        String username = loginEntity.getUsername();
        String password = loginEntity.getPassword();
        String captchaKey = loginEntity.getCaptchaKey();
        String captchaText = loginEntity.getCaptchaText();
        if (ObjectUtils.anyNull(username, password, captchaKey, captchaText)) {
            throw new BusinessException();
        }
        return Mono.just(loginEntity)
                .flatMap(inner -> this.reactiveRedisTemplate.opsForValue().get(captchaKey))
                .switchIfEmpty(Mono.error(() -> new BusinessException("验证码错误")))
                .flatMap(inner -> {
                            SystemUser systemUser = this.lambdaQuery()
                                    .eq(SystemUser::getUsername, username)
                                    .oneOpt()
                                    .orElseThrow(() -> new BusinessException("用户不存在或密码错误"));

                            if (!BCrypt.checkpw(password, systemUser.getPassword())) {
                                return Mono.error(new BusinessException("用户不存在或密码错误"));
                            }
                            if (Objects.equals(systemUser.getState(), CommonStateEnum.DISABLE.getCode())) {
                                return Mono.error(new BusinessException("账号已禁用"));
                            }
                            return Mono.just(systemUser);
                        }
                )
                .doOnNext(inner -> StpUtil.login(inner.getId()))
                .map(inner -> StpUtil.getTokenInfo())
                .subscribeOn(Schedulers.boundedElastic());
    }

< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by ly-chn** [comment]
![ca34b753fd1aba13a7d5ef13630af7ba](https://github.com/dromara/Sa-Token/assets/37045167/8a8ead66-dd26-4f95-8a04-717325590cf8)
参考群友解决方案, Mono.just为 yibu shangxiawen
cao shurufa sidiao le
