### ISSUE TITLE
 StpUtil.login(loginUser.getUserId()); 报错SaTokenContextException: 未能获取有效的上下文

### ISSUE THREAD

**Issue by Suki001** [dromara/Sa-Token#668]
### 使用版本:
SpringBoot 3.3 
sa-token-reactor-spring-boot3-starter 1.38.0

### 涉及的功能模块：

StpUtil.login(loginUser.getUserId());报错cn.dev33.satoken.exception.SaTokenContextException: 未能获取有效的上下文
at cn.dev33.satoken.context.SaTokenContextForThreadLocalStorage.getBoxNotNull(SaTokenContextForThreadLocalStorage.java:72) ~[sa-token-core-1.38.0.jar:na]
	at cn.dev33.satoken.context.SaTokenContextForThreadLocalStorage.getStorage(SaTokenContextForThreadLocalStorage.java:101) ~[sa-token-core-1.38.0.jar:na]
	at cn.dev33.satoken.context.SaTokenContextForThreadLocal.getStorage(SaTokenContextForThreadLocal.java:49) ~[sa-token-core-1.38.0.jar:na]
	at cn.dev33.satoken.context.SaHolder.getStorage(SaHolder.java:69) ~[sa-token-core-1.38.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.setTokenValueToStorage(StpLogic.java:218) ~[sa-token-core-1.38.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.setTokenValue(StpLogic.java:198) ~[sa-token-core-1.38.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:441) ~[sa-token-core-1.38.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:397) ~[sa-token-core-1.38.0.jar:na]
	at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:164) ~[sa-token-core-1.38.0.jar:na]

### 测试步骤：

SaTokenContextForThreadLocalStorage 中的setBox方法没找到引用的地方，所以get的时候为空？需要有什么额外的配置吗？

**Comment by Suki001** [comment]
依赖用错了了，应该是sa-token-spring-boot3-starter 1.38.0
