### ISSUE TITLE
非 web 上下文无法获取 HttpServletRequest

### ISSUE THREAD

**Issue by wayhelper** [dromara/Sa-Token#692]
### 使用版本:
1.39.0

### 报错信息：
2024-10-11T17:32:49.810+08:00 ERROR 24884 --- [nio-5201-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: cn.dev33.satoken.exception.NotWebContextException: 非 web 上下文无法获取 HttpServletRequest] with root cause

cn.dev33.satoken.exception.NotWebContextException: 非 web 上下文无法获取 HttpServletRequest
	at cn.dev33.satoken.spring.SpringMVCUtil.getRequest(SpringMVCUtil.java:44) ~[sa-token-spring-boot3-starter-1.39.0.jar:na]
	at cn.dev33.satoken.spring.SaTokenContextForSpringInJakartaServlet.getStorage(SaTokenContextForSpringInJakartaServlet.java:56) ~[sa-token-spring-boot3-starter-1.39.0.jar:na]
	at cn.dev33.satoken.context.SaHolder.getStorage(SaHolder.java:69) ~[sa-token-core-1.39.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.setTokenValueToStorage(StpLogic.java:218) ~[sa-token-core-1.39.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.setTokenValue(StpLogic.java:198) ~[sa-token-core-1.39.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:441) ~[sa-token-core-1.39.0.jar:na]
	at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:397) ~[sa-token-core-1.39.0.jar:na]
	at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:164) ~[sa-token-core-1.39.0.jar:na]
	at org.jason.oauth2.dao.impl.UserDao.lambda$login$0(UserDao.java:37) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]

### 问题描述：
好吧我并没可用的服务器资源，因此我在模拟测试登录时使用的是一个for循环。但执行一段时间后额可能是几秒钟，出现此错误，因此我不确定当用户量足够多时是否会出现此异常。如果我的使用不正确请给我些暗示。谢谢！

### 复现步骤：
`    
  @Override
      public Object login() {
          List<Integer> list = new ArrayList<>();
          for (int i=0; i < 1000; i++) {
              list.add(i);
          }
          list.parallelStream().forEach(i->{
              StpUtil.login(i);
          });
          return true;
      }
`

< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by ly-chn** [comment]
有意思，首先这个异常你可以从官网看到，也就是因为当前线程不在http请求中，所以登录时无法正常处理请求和响应信息，所以sa-token抛出了这个异常至于for登录嘛，应该单独写个程序测试，否则很难验证承载量的在 2024年10月11日，17:40，景伟·郭 ***@***.***> 写道：﻿
使用版本:
1.39.0
报错信息：
2024-10-11T17:32:49.810+08:00 ERROR 24884 --- [nio-5201-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: cn.dev33.satoken.exception.NotWebContextException: 非 web 上下文无法获取 HttpServletRequest] with root cause
cn.dev33.satoken.exception.NotWebContextException: 非 web 上下文无法获取 HttpServletRequest
at cn.dev33.satoken.spring.SpringMVCUtil.getRequest(SpringMVCUtil.java:44) ~[sa-token-spring-boot3-starter-1.39.0.jar:na]
at cn.dev33.satoken.spring.SaTokenContextForSpringInJakartaServlet.getStorage(SaTokenContextForSpringInJakartaServlet.java:56) ~[sa-token-spring-boot3-starter-1.39.0.jar:na]
at cn.dev33.satoken.context.SaHolder.getStorage(SaHolder.java:69) ~[sa-token-core-1.39.0.jar:na]
at cn.dev33.satoken.stp.StpLogic.setTokenValueToStorage(StpLogic.java:218) ~[sa-token-core-1.39.0.jar:na]
at cn.dev33.satoken.stp.StpLogic.setTokenValue(StpLogic.java:198) ~[sa-token-core-1.39.0.jar:na]
at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:441) ~[sa-token-core-1.39.0.jar:na]
at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:397) ~[sa-token-core-1.39.0.jar:na]
at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:164) ~[sa-token-core-1.39.0.jar:na]
at org.jason.oauth2.dao.impl.UserDao.lambda$login$0(UserDao.java:37) ~[classes/:na]
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373) ~[na:na]
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
问题描述：
好吧我并没可用的服务器资源，因此我在模拟测试登录时使用的是一个for循环。但执行过程中出现此错误，因此我不确定当用户量足够多时是否会出现此异常。如果我的使用不正确请给我些暗示。谢谢！
复现步骤：
    @Override public Object login() { List<Integer> list = new ArrayList<>(); for (int i=0; i < 1000; i++) { list.add(i); } list.parallelStream().forEach(i->{ StpUtil.login(i); }); return true; }
< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by click33** [comment]
可以参考一下排查手册：
![image](https://github.com/user-attachments/assets/15d71c7a-e3c6-4707-90f4-f759c7402baf)

https://sa-token.cc/doc.html#/more/common-questions?id=q%ef%bc%9a%e6%8a%a5%e9%94%99%ef%bc%9a%e9%9d%9e-web-%e4%b8%8a%e4%b8%8b%e6%96%87%e6%97%a0%e6%b3%95%e8%8e%b7%e5%8f%96-httpservletrequest%e3%80%82



另外，如果要在单个请求内模拟登录几万次，请关闭cookie模式（配置文件：sa-token.is-read-cookie=false），因为开启cookie模式的情况下，每次登录都会增加一个 Set-Cookie 的响应头，登录几万次就会有几万个，最后导致响应头溢出了
