### ISSUE TITLE
sping boot3 无法集成jwt 报错

### ISSUE THREAD

**Issue by yoke0104x** [dromara/Sa-Token#704]
### 使用版本:
sa-token-spring-boot3-starter: 1.34.0
sa-token-jwt: 1.34.0 和1.39.0

### 报错信息：
`
jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoSuchMethodError: 'cn.dev33.satoken.config.SaTokenConfig cn.dev33.satoken.jwt.StpLogicJwtForSimple.getConfigOrGlobal()'
 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1104)
 at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
 at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
 at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
 at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
 at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
 at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
 at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
 at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384)
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
 at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
 at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
 at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoSuchMethodError: 'cn.dev33.satoken.config.SaTokenConfig cn.dev33.satoken.jwt.StpLogicJwtForSimple.getConfigOrGlobal()'
 at cn.dev33.satoken.jwt.StpLogicJwtForSimple.jwtSecretKey(StpLogicJwtForSimple.java:53)
 at cn.dev33.satoken.jwt.StpLogicJwtForSimple.createTokenValue(StpLogicJwtForSimple.java:65)
 at cn.dev33.satoken.stp.StpLogic.distUsableToken(StpLogic.java:424)
 at cn.dev33.satoken.stp.StpLogic.createLoginSession(StpLogic.java:362)
 at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:331)
 at cn.dev33.satoken.stp.StpLogic.login(StpLogic.java:293)
 at cn.dev33.satoken.stp.StpUtil.login(StpUtil.java:135)
 at fan.fantasy.service.impl.UserServiceImpl.login(UserServiceImpl.java:50)
 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
 at java.base/java.lang.reflect.Method.invoke(Method.java:580)
 at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716)
 at fan.fantasy.service.impl.UserServiceImpl$$SpringCGLIB$$0.login(<generated>)
 at fan.fantasy.controller.UserController.login(UserController.java:45)
 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
 at java.base/java.lang.reflect.Method.invoke(Method.java:580)
 at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
 at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
 at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
 ... 39 more
`

### 希望结果：
`
可以正常使用
`

### 复现步骤：
无

**Comment by click33** [comment]
微信sa-token小助手已回复
