### ISSUE TITLE
'cn.dev33.satoken.dao.alone.SaAloneRedisInject': io/lettuce/core/ClientOptions

### ISSUE THREAD

**Issue by bruce-pang** [dromara/Sa-Token#710]
### 使用版本:
sa-token-alone-redis:1.39.0

### 报错信息：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cn.dev33.satoken.dao.alone.SaAloneRedisInject': io/lettuce/core/ClientOptions
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:606)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at com.jikongmro.bulk.server.JkServerApplication.main(JkServerApplication.java:26)
Caused by: java.lang.NoClassDefFoundError: io/lettuce/core/ClientOptions
	at org.springframework.data.redis.connection.lettuce.LettuceClientConfiguration$LettuceClientConfigurationBuilder.<init>(LettuceClientConfiguration.java:172)
	at org.springframework.data.redis.connection.lettuce.LettucePoolingClientConfiguration$LettucePoolingClientConfigurationBuilder.<init>(LettucePoolingClientConfiguration.java:97)
	at org.springframework.data.redis.connection.lettuce.LettucePoolingClientConfiguration.builder(LettucePoolingClientConfiguration.java:51)
	at cn.dev33.satoken.dao.alone.SaAloneRedisInject.setEnvironment(SaAloneRedisInject.java:195)
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:94)
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:421)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1765)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	... 15 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.lettuce.core.ClientOptions
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 24 common frames omitted

### 复现步骤：
在jdk17+springboot3.2.2环境中
在Spring配置文件添加如下配置
# saToken配置
sa-token:
  # 是否输出操作日志
  is-log: true
  alone-redis:
    database: 14
    host: 192.168.122.1
    port: 6379
    password: 123456
    timeout: 10
    lettuce:
      pool:
        max-active: 50       # 最大连接数
        max-idle: 10         # 最大空闲连接数
        min-idle: 5          # 最小空闲连接数
        max-wait: 2000ms     # 连接池最大等待时间
启动项目报错上述错误，
< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >

**Comment by bruce-pang** [comment]
项目中所有涉及到的satoken依赖如图
![image](https://github.com/user-attachments/assets/50463fc7-20f1-45b7-bb37-f3b68e86d147)

**Comment by click33** [comment]
已通过独立插件 `sa-token-alone-redisson` 解决：Redisson 场景下权限缓存与业务缓存分离，支持单机 / 集群原生 yaml。

文档：https://sa-token.com/#/plugin/alone-redisson
